apiVersion: kibana.k8s.elastic.co/v1alpha1
kind: Kibana
metadata:
  name: quickstart
  namespace: elasticsearch
spec:
  version: 7.2.0
  nodeCount: 1
  elasticsearchRef:
    name: quickstart

  podTemplate:
    # metadata:
    #   labels:
    #     foo: bar
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: 4Gi
            cpu: 1500m
          request:
            memory: 4Gi
            cpu: 1500m
