# doc: http://docs.cert-manager.io/en/latest/reference/issuers/acme/dns01.html
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: issuer-dns01
spec:
  acme:
    email: devops@managedkube.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-private-key
    dns01:
      providers:
      - name: prod
        route53:
          region: us-east-1

          # optional if ambient credentials are available; see ambient credentials documentation
          accessKeyID: foo
          secretAccessKeySecretRef:
            name: aws-route53-credentials-secret
            key: secret-access-key
