{{- if .Values.issuer.http.enabled }}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: issuer-http01
spec:
  acme:
    # The ACME server URL
    server: {{ .Values.letsencrypt.server }}
    # Email address used for ACME registration
    email: {{ .Values.email }}
    # Name of a secret used to store the ACME account private key from step 3
    privateKeySecretRef:
      name: letsencrypt-private-key
    # Enable the HTTP-01 challenge provider
    http01: {}

{{- end }}
