# doc: http://docs.cert-manager.io/en/latest/reference/issuers/acme/dns01.html
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: issuer-dns01
spec:
  acme:
    email: devops@expanse.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-private-key
    dns01:
      providers:
      - name: prod
        clouddns:
          project: elasticsearch-204100
          serviceAccountSecretRef:
            name: gcp-clouddns-service-account
            key: service-account.json
